version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sms"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1jitzv7zfs8nr"
s3_prefix = "sms"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"

