AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Sample SAM Template for sms sending

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  SNSorPinpoint:
    Type: String
    Default: Pinpoint
    Description: Backend Application.
  PinPointID:
    Type: String
    Default: "1d205f0b0bb54f1a8499e1e60ce7f553"
    Description: Amazon Pinpint Application ID.
  SecurityGroupIds: 
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: Security Group IDs that Lambda will use
  VpcSubnetIds: 
    Type: List<AWS::EC2::Subnet::Id>
    Description: VPC Subnet IDs that Lambda will use (min 2 for HA)

Resources:
  SMSGatewayFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: smsGateway.handler
      Runtime: python3.8
      Environment:
        Variables:
          SNSorPinpoint: !Ref SNSorPinpoint
          PinPointID: !Ref PinPointID
      Events:
        SmsSendAPI:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref SmsSendApi
            Path: /sms
            Method: POST
        SmsBatchSendAPI:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref SmsSendApi
            Path: /smsBatch
            Method: POST
        SmsTemplateCreateAPI:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            ApiId: !Ref SmsTemplateApi
            Path: /smsTemplateCreate
            Method: POST
      Policies:
        # - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action: mobiletargeting:*
              Resource: '*'

  SmsSendApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      # Name: SendSMS
      StageName: Prod
      # omit in lambda proxy, more on https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
      # Cors:
      #   AllowMethods: "'*'"
      #   AllowHeaders: "'*'"
      #   AllowOrigin: "'http://localhost:8080'"
      #   MaxAge: "'600'"
      #   AllowCredentials: True
      # Auth:
      #   ApiKeyRequired: false # OPTIONAL
      #   UsagePlan: # OPTIONAL
      #     CreateUsagePlan: NONE # REQUIRED if UsagePlan property is set. accepted values: PER_API, SHARED, NONE
      #   DefaultAuthorizer: MyCognitoAuth # OPTIONAL, if you use IAM permissions, specify AWS_IAM.
      #   AddDefaultAuthorizerToCorsPreflight: false # OPTIONAL; Default: true
      #   ResourcePolicy:
      #     CustomStatements:
      #       - Effect: Allow
      #         Principal: *
      #         Action: execute-api:Invoke
      #     #   ...
      #     # AwsAccountWhitelist: [<list of account ids>]
      #     # AwsAccountBlacklist: [<list of account ids>]
      #     # IpRangeWhitelist: [<list of ip ranges>]
      #     # IpRangeBlacklist: [<list of ip ranges>]
      #     # SourceVpcWhitelist: [<list of vpc/vpce endpoint ids>]
      #     # SourceVpcBlacklist: [<list of vpc/vpce endpoint ids>]
      #   # For AWS_IAM:
      #   # DefaultAuthorizer: AWS_IAM
      #   # InvokeRole: NONE # CALLER_CREDENTIALS by default unless overridden
      #     Authorizers: MyCognitoAuth
      #       MyCognitoAuth:
      #         UserPoolArn: !GetAtt MyCognitoUserPool.Arn # Can also accept an array
      #         AuthorizationScopes:
      #           - scope1 # List of authorization scopes
      #         Identity: # OPTIONAL
      #           Header: MyAuthorizationHeader # OPTIONAL; Default: 'Authorization'
      #           ValidationExpression: myauthvalidationexpression # OPTIONAL

  SmsTemplateApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod

  SMSDeliveryReceiptFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: smsStream.handler
      Runtime: python3.8
      Timeout: 10
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetIds: !Ref VpcSubnetIds
      # Tracing: Active
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt DeliveryReceiptStream.Arn
            BatchSize: 100
            MaximumRetryAttempts: 10
            MaximumBatchingWindowInSeconds: 30
            StartingPosition: LATEST

  DeliveryReceiptStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SmsSendApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for SMS sending function"
    Value: !Sub "https://${SmsSendApi}.execute-api.${AWS::Region}.amazonaws.com/${SmsSendApi.Stage}/sms/"
  SmsBatchSendApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for SMS batch sending function"
    Value: !Sub "https://${SmsSendApi}.execute-api.${AWS::Region}.amazonaws.com/${SmsSendApi.Stage}/smsBatch/"
  SmsTemplateCreateApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for SMS template create function"
    Value: !Sub "https://${SmsTemplateApi}.execute-api.${AWS::Region}.amazonaws.com/${SmsTemplateApi.Stage}/smsTemplateCreate/"
  SMSGatewayFunction:
    Description: "SMSGatewayFunction Lambda Function ARN"
    Value: !GetAtt SMSGatewayFunction.Arn
  SMSDeliveryReceiptFunction:
    Description: "SMSDeliveryReceiptFunction Lambda Function"
    Value: !Ref SMSDeliveryReceiptFunction
  DeliveryReceiptStream:
    Description: "DeliveryReceiptStream ARN"
    Value: !GetAtt DeliveryReceiptStream.Arn
