AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >

  Sample SAM Template for sms sending

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  PinPointID:
    Type: String
    Default: "1234567890"
    Description: Amazon Pinpint Application ID.

Resources:
  EventFanout:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.pinpoint_handler
      Runtime: python3.8
      Environment:
        Variables:
          PinPointID: !Ref PinPointID
      Events:
        SmsSend:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sms
            Method: POST
      # Policies:
      #     - SNSCrudPolicy:
      #       Description: 'SNS policy'
      #       Statement:
      #         - Effect: Allow
      #           Action:
      #             - sns: '*'
      #           Resource: '*'
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SmsSendApi:
    Description: "API Gateway endpoint URL for Prod stage for EventFanout function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/sms/"
  EventFanout:
    Description: "EventFanout Lambda Function ARN"
    Value: !GetAtt EventFanout.Arn
  EventFanoutIamRole:
    Description: "Implicit IAM Role created for EventFanout function"
    Value: !GetAtt EventFanoutRole.Arn
