version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fanout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1aji2ogv3451f"
s3_prefix = "fanout"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBStreamArn=\"arn:aws:dynamodb:ap-northeast-1:275937937240:table/HackathonTable/stream/2020-04-24T08:10:33.200\" EventBusName=\"fanoutBus\" EventBridgeMaxAttempt=\"3\""

